// src/lib/harness/harness-spec.ts
// Generated by Agent Alpha — Phase 1.1
// Date: 2026-06-30

import type { IrItemType } from '../htse/ir-types';

// DrakonHarnessSpec moved to @ai-drakon/harness-contract (Phase 2 Slice 2)
// -- re-exported here so every existing import of this module keeps
// working unchanged.
export { validateHarnessSpec, createDefaultSpec } from '@ai-drakon/harness-contract';
export type { DrakonHarnessSpec } from '@ai-drakon/harness-contract';

