// src/lib/harness/pipeline-client.ts
// Generated by Agent Beta — Phase 1.4
// Replaces: SSE direct connection to FastAPI architect-agent
// Uses: Appwrite Function async execution + polling (same pattern as codegen/compile)

// DrakonHarnessSpec, GateVerdict and PipelineEvent moved to
// @ai-drakon/harness-contract (Phase 2 Slice 2) -- re-exported here so
// every existing import of this module keeps working unchanged.
export type { DrakonHarnessSpec, GateVerdict, PipelineEvent } from '@ai-drakon/harness-contract';
import type { DrakonHarnessSpec, PipelineEvent } from '@ai-drakon/harness-contract';

export interface PipelineClientOptions {
  workerBaseUrl: string;
  authToken?: string;         // Bearer token sent on both execute and status-poll requests
  pollingIntervalMs?: number;  // default: 2500
  maxPollingAttempts?: number; // default: 120 (5 minutes)
}

export class DeterministicPipelineClient {
  constructor(private opts: PipelineClientOptions) {}

  async execute(
    drakonIr: unknown,
    harnessSpec: DrakonHarnessSpec,
    callbacks: {
      onEvent: (event: PipelineEvent) => void;
      onComplete: (events: PipelineEvent[]) => void;
      onError: (error: Error) => void;
    },
    breakpoints: string[] = [],
  ): Promise<void> {
    try {
      // 1. POST to start execution - starts deterministic engine
      const startRes = await fetch(`${this.opts.workerBaseUrl}/v1/pipeline/execute-deterministic`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(this.opts.authToken ? { Authorization: `Bearer ${this.opts.authToken}` } : {}),
        },
        body: JSON.stringify({
          drakon_ir: drakonIr,
          harness_spec: harnessSpec,
          breakpoints,
        }),
      });

      if (!startRes.ok) {
        const errText = await startRes.text().catch(() => '');
        callbacks.onError(new Error(`Failed to start pipeline: ${startRes.status} ${errText}`));
        return;
      }

      const { execution_id } = await startRes.json();
      if (!execution_id) {
        callbacks.onError(new Error('No execution_id returned from gateway'));
        return;
      }

      // 2. Poll for completion
      const interval = this.opts.pollingIntervalMs ?? 2500;
      const maxAttempts = this.opts.maxPollingAttempts ?? 120;
      let attempts = 0;

      while (attempts < maxAttempts) {
        await sleep(interval);
        attempts++;

        const pollRes = await fetch(
          `${this.opts.workerBaseUrl}/v1/pipeline/execute-deterministic/status?execution_id=${execution_id}`,
          {
            headers: this.opts.authToken ? { Authorization: `Bearer ${this.opts.authToken}` } : {},
          }
        );

        if (!pollRes.ok) {
          callbacks.onError(new Error(`Status check failed: ${pollRes.status}`));
          return;
        }

        const poll = await pollRes.json();

        // Progressive event emissions if status update contains them
        if (poll.events && Array.isArray(poll.events)) {
          // Replay events to update UI
          for (const evt of poll.events) {
            callbacks.onEvent(evt);
          }
        }

        if (poll.status === 'completed') {
          const events: PipelineEvent[] = poll.events ?? [];
          callbacks.onComplete(events);
          return;
        }

        if (poll.status === 'failed') {
          callbacks.onError(new Error(poll.error ?? 'Execution failed'));
          return;
        }

        // If status === 'processing' or 'waiting', keep polling
      }

      callbacks.onError(new Error('Pipeline execution polling timed out after 5 minutes'));
    } catch (err) {
      callbacks.onError(err instanceof Error ? err : new Error(String(err)));
    }
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
