name = "drakon-antigravity-worker"
main = "worker-mcp-drakon.js"
compatibility_date = "2024-01-01"
account_id = "c354ea45a11a1e1c14f1f41fe780cb34"

[vars]
DRAKON_CODEGEN_FUNCTION_ID = "6a33b6050037a2fff34e"
MCP_API_KEY = "drakon-mcp-2026"

[[services]]
binding = "DOCS_AGENT"
service = "docs-agent-flue"

[[services]]
binding = "ARCHITECT_AGENT"
service = "architect-agent-flue"
