/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as NotebooksRouteImport } from './routes/notebooks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as GithubRouteImport } from './routes/github'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DiagramsRouteImport } from './routes/diagrams'
import { Route as DevcycleRouteImport } from './routes/devcycle'
import { Route as CodegenRouteImport } from './routes/codegen'
import { Route as CodeRouteImport } from './routes/code'
import { Route as ArchitectRouteImport } from './routes/architect'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectNewRouteImport } from './routes/project.new'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as DiagramEditorRouteImport } from './routes/diagram.editor'
import { Route as PipelinePipelineIdEditRouteImport } from './routes/pipeline.$pipelineId.edit'
import { Route as PSlugSettingsRouteImport } from './routes/p.$slug.settings'
import { Route as PSlugPlaypipeRouteImport } from './routes/p.$slug.playpipe'
import { Route as PSlugOverviewRouteImport } from './routes/p.$slug.overview'
import { Route as PSlugDocsRouteImport } from './routes/p.$slug.docs'
import { Route as PSlugAutomationsRouteImport } from './routes/p.$slug.automations'
import { Route as PSlugAgentsRouteImport } from './routes/p.$slug.agents'
import { Route as ApiNotebooklmNotebooksRouteImport } from './routes/api.notebooklm.notebooks'
import { Route as ApiNotebooklmChatRouteImport } from './routes/api.notebooklm.chat'
import { Route as ApiKnowledgeZonesRouteImport } from './routes/api.knowledge.zones'
import { Route as ApiKnowledgeZonesZoneIdRouteImport } from './routes/api.knowledge.zones.$zoneId'
import { Route as ApiKnowledgeZonesZoneIdNotebooklmRouteImport } from './routes/api.knowledge.zones.$zoneId.notebooklm'
import { Route as ApiKnowledgeZonesZoneIdNotebooklmRetryRouteImport } from './routes/api.knowledge.zones.$zoneId.notebooklm.retry'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksRoute = NotebooksRouteImport.update({
  id: '/notebooks',
  path: '/notebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramsRoute = DiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => rootRouteImport,
} as any)
const DevcycleRoute = DevcycleRouteImport.update({
  id: '/devcycle',
  path: '/devcycle',
  getParentRoute: () => rootRouteImport,
} as any)
const CodegenRoute = CodegenRouteImport.update({
  id: '/codegen',
  path: '/codegen',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectRoute = ArchitectRouteImport.update({
  id: '/architect',
  path: '/architect',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectNewRoute = ProjectNewRouteImport.update({
  id: '/project/new',
  path: '/project/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramEditorRoute = DiagramEditorRouteImport.update({
  id: '/diagram/editor',
  path: '/diagram/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinePipelineIdEditRoute = PipelinePipelineIdEditRouteImport.update({
  id: '/$pipelineId/edit',
  path: '/$pipelineId/edit',
  getParentRoute: () => PipelineRoute,
} as any)
const PSlugSettingsRoute = PSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugPlaypipeRoute = PSlugPlaypipeRouteImport.update({
  id: '/playpipe',
  path: '/playpipe',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugOverviewRoute = PSlugOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugDocsRoute = PSlugDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugAutomationsRoute = PSlugAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugAgentsRoute = PSlugAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => PSlugRoute,
} as any)
const ApiNotebooklmNotebooksRoute = ApiNotebooklmNotebooksRouteImport.update({
  id: '/api/notebooklm/notebooks',
  path: '/api/notebooklm/notebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotebooklmChatRoute = ApiNotebooklmChatRouteImport.update({
  id: '/api/notebooklm/chat',
  path: '/api/notebooklm/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeZonesRoute = ApiKnowledgeZonesRouteImport.update({
  id: '/api/knowledge/zones',
  path: '/api/knowledge/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeZonesZoneIdRoute = ApiKnowledgeZonesZoneIdRouteImport.update({
  id: '/$zoneId',
  path: '/$zoneId',
  getParentRoute: () => ApiKnowledgeZonesRoute,
} as any)
const ApiKnowledgeZonesZoneIdNotebooklmRoute =
  ApiKnowledgeZonesZoneIdNotebooklmRouteImport.update({
    id: '/notebooklm',
    path: '/notebooklm',
    getParentRoute: () => ApiKnowledgeZonesZoneIdRoute,
  } as any)
const ApiKnowledgeZonesZoneIdNotebooklmRetryRoute =
  ApiKnowledgeZonesZoneIdNotebooklmRetryRouteImport.update({
    id: '/retry',
    path: '/retry',
    getParentRoute: () => ApiKnowledgeZonesZoneIdNotebooklmRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architect': typeof ArchitectRoute
  '/code': typeof CodeRoute
  '/codegen': typeof CodegenRoute
  '/devcycle': typeof DevcycleRoute
  '/diagrams': typeof DiagramsRoute
  '/docs': typeof DocsRoute
  '/github': typeof GithubRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/notebooks': typeof NotebooksRoute
  '/observability': typeof ObservabilityRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/pipelines': typeof PipelinesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sync': typeof SyncRoute
  '/workspace': typeof WorkspaceRoute
  '/diagram/editor': typeof DiagramEditorRoute
  '/editor/$id': typeof EditorIdRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/project/new': typeof ProjectNewRoute
  '/api/knowledge/zones': typeof ApiKnowledgeZonesRouteWithChildren
  '/api/notebooklm/chat': typeof ApiNotebooklmChatRoute
  '/api/notebooklm/notebooks': typeof ApiNotebooklmNotebooksRoute
  '/p/$slug/agents': typeof PSlugAgentsRoute
  '/p/$slug/automations': typeof PSlugAutomationsRoute
  '/p/$slug/docs': typeof PSlugDocsRoute
  '/p/$slug/overview': typeof PSlugOverviewRoute
  '/p/$slug/playpipe': typeof PSlugPlaypipeRoute
  '/p/$slug/settings': typeof PSlugSettingsRoute
  '/pipeline/$pipelineId/edit': typeof PipelinePipelineIdEditRoute
  '/api/knowledge/zones/$zoneId': typeof ApiKnowledgeZonesZoneIdRouteWithChildren
  '/api/knowledge/zones/$zoneId/notebooklm': typeof ApiKnowledgeZonesZoneIdNotebooklmRouteWithChildren
  '/api/knowledge/zones/$zoneId/notebooklm/retry': typeof ApiKnowledgeZonesZoneIdNotebooklmRetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architect': typeof ArchitectRoute
  '/code': typeof CodeRoute
  '/codegen': typeof CodegenRoute
  '/devcycle': typeof DevcycleRoute
  '/diagrams': typeof DiagramsRoute
  '/docs': typeof DocsRoute
  '/github': typeof GithubRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/notebooks': typeof NotebooksRoute
  '/observability': typeof ObservabilityRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/pipelines': typeof PipelinesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sync': typeof SyncRoute
  '/workspace': typeof WorkspaceRoute
  '/diagram/editor': typeof DiagramEditorRoute
  '/editor/$id': typeof EditorIdRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/project/new': typeof ProjectNewRoute
  '/api/knowledge/zones': typeof ApiKnowledgeZonesRouteWithChildren
  '/api/notebooklm/chat': typeof ApiNotebooklmChatRoute
  '/api/notebooklm/notebooks': typeof ApiNotebooklmNotebooksRoute
  '/p/$slug/agents': typeof PSlugAgentsRoute
  '/p/$slug/automations': typeof PSlugAutomationsRoute
  '/p/$slug/docs': typeof PSlugDocsRoute
  '/p/$slug/overview': typeof PSlugOverviewRoute
  '/p/$slug/playpipe': typeof PSlugPlaypipeRoute
  '/p/$slug/settings': typeof PSlugSettingsRoute
  '/pipeline/$pipelineId/edit': typeof PipelinePipelineIdEditRoute
  '/api/knowledge/zones/$zoneId': typeof ApiKnowledgeZonesZoneIdRouteWithChildren
  '/api/knowledge/zones/$zoneId/notebooklm': typeof ApiKnowledgeZonesZoneIdNotebooklmRouteWithChildren
  '/api/knowledge/zones/$zoneId/notebooklm/retry': typeof ApiKnowledgeZonesZoneIdNotebooklmRetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architect': typeof ArchitectRoute
  '/code': typeof CodeRoute
  '/codegen': typeof CodegenRoute
  '/devcycle': typeof DevcycleRoute
  '/diagrams': typeof DiagramsRoute
  '/docs': typeof DocsRoute
  '/github': typeof GithubRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/notebooks': typeof NotebooksRoute
  '/observability': typeof ObservabilityRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/pipelines': typeof PipelinesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sync': typeof SyncRoute
  '/workspace': typeof WorkspaceRoute
  '/diagram/editor': typeof DiagramEditorRoute
  '/editor/$id': typeof EditorIdRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/project/new': typeof ProjectNewRoute
  '/api/knowledge/zones': typeof ApiKnowledgeZonesRouteWithChildren
  '/api/notebooklm/chat': typeof ApiNotebooklmChatRoute
  '/api/notebooklm/notebooks': typeof ApiNotebooklmNotebooksRoute
  '/p/$slug/agents': typeof PSlugAgentsRoute
  '/p/$slug/automations': typeof PSlugAutomationsRoute
  '/p/$slug/docs': typeof PSlugDocsRoute
  '/p/$slug/overview': typeof PSlugOverviewRoute
  '/p/$slug/playpipe': typeof PSlugPlaypipeRoute
  '/p/$slug/settings': typeof PSlugSettingsRoute
  '/pipeline/$pipelineId/edit': typeof PipelinePipelineIdEditRoute
  '/api/knowledge/zones/$zoneId': typeof ApiKnowledgeZonesZoneIdRouteWithChildren
  '/api/knowledge/zones/$zoneId/notebooklm': typeof ApiKnowledgeZonesZoneIdNotebooklmRouteWithChildren
  '/api/knowledge/zones/$zoneId/notebooklm/retry': typeof ApiKnowledgeZonesZoneIdNotebooklmRetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/architect'
    | '/code'
    | '/codegen'
    | '/devcycle'
    | '/diagrams'
    | '/docs'
    | '/github'
    | '/knowledge'
    | '/login'
    | '/notebooks'
    | '/observability'
    | '/pipeline'
    | '/pipelines'
    | '/settings'
    | '/sitemap.xml'
    | '/sync'
    | '/workspace'
    | '/diagram/editor'
    | '/editor/$id'
    | '/p/$slug'
    | '/project/new'
    | '/api/knowledge/zones'
    | '/api/notebooklm/chat'
    | '/api/notebooklm/notebooks'
    | '/p/$slug/agents'
    | '/p/$slug/automations'
    | '/p/$slug/docs'
    | '/p/$slug/overview'
    | '/p/$slug/playpipe'
    | '/p/$slug/settings'
    | '/pipeline/$pipelineId/edit'
    | '/api/knowledge/zones/$zoneId'
    | '/api/knowledge/zones/$zoneId/notebooklm'
    | '/api/knowledge/zones/$zoneId/notebooklm/retry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/architect'
    | '/code'
    | '/codegen'
    | '/devcycle'
    | '/diagrams'
    | '/docs'
    | '/github'
    | '/knowledge'
    | '/login'
    | '/notebooks'
    | '/observability'
    | '/pipeline'
    | '/pipelines'
    | '/settings'
    | '/sitemap.xml'
    | '/sync'
    | '/workspace'
    | '/diagram/editor'
    | '/editor/$id'
    | '/p/$slug'
    | '/project/new'
    | '/api/knowledge/zones'
    | '/api/notebooklm/chat'
    | '/api/notebooklm/notebooks'
    | '/p/$slug/agents'
    | '/p/$slug/automations'
    | '/p/$slug/docs'
    | '/p/$slug/overview'
    | '/p/$slug/playpipe'
    | '/p/$slug/settings'
    | '/pipeline/$pipelineId/edit'
    | '/api/knowledge/zones/$zoneId'
    | '/api/knowledge/zones/$zoneId/notebooklm'
    | '/api/knowledge/zones/$zoneId/notebooklm/retry'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/architect'
    | '/code'
    | '/codegen'
    | '/devcycle'
    | '/diagrams'
    | '/docs'
    | '/github'
    | '/knowledge'
    | '/login'
    | '/notebooks'
    | '/observability'
    | '/pipeline'
    | '/pipelines'
    | '/settings'
    | '/sitemap.xml'
    | '/sync'
    | '/workspace'
    | '/diagram/editor'
    | '/editor/$id'
    | '/p/$slug'
    | '/project/new'
    | '/api/knowledge/zones'
    | '/api/notebooklm/chat'
    | '/api/notebooklm/notebooks'
    | '/p/$slug/agents'
    | '/p/$slug/automations'
    | '/p/$slug/docs'
    | '/p/$slug/overview'
    | '/p/$slug/playpipe'
    | '/p/$slug/settings'
    | '/pipeline/$pipelineId/edit'
    | '/api/knowledge/zones/$zoneId'
    | '/api/knowledge/zones/$zoneId/notebooklm'
    | '/api/knowledge/zones/$zoneId/notebooklm/retry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ArchitectRoute: typeof ArchitectRoute
  CodeRoute: typeof CodeRoute
  CodegenRoute: typeof CodegenRoute
  DevcycleRoute: typeof DevcycleRoute
  DiagramsRoute: typeof DiagramsRoute
  DocsRoute: typeof DocsRoute
  GithubRoute: typeof GithubRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  NotebooksRoute: typeof NotebooksRoute
  ObservabilityRoute: typeof ObservabilityRoute
  PipelineRoute: typeof PipelineRouteWithChildren
  PipelinesRoute: typeof PipelinesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SyncRoute: typeof SyncRoute
  WorkspaceRoute: typeof WorkspaceRoute
  DiagramEditorRoute: typeof DiagramEditorRoute
  EditorIdRoute: typeof EditorIdRoute
  PSlugRoute: typeof PSlugRouteWithChildren
  ProjectNewRoute: typeof ProjectNewRoute
  ApiKnowledgeZonesRoute: typeof ApiKnowledgeZonesRouteWithChildren
  ApiNotebooklmChatRoute: typeof ApiNotebooklmChatRoute
  ApiNotebooklmNotebooksRoute: typeof ApiNotebooklmNotebooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks': {
      id: '/notebooks'
      path: '/notebooks'
      fullPath: '/notebooks'
      preLoaderRoute: typeof NotebooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagrams': {
      id: '/diagrams'
      path: '/diagrams'
      fullPath: '/diagrams'
      preLoaderRoute: typeof DiagramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devcycle': {
      id: '/devcycle'
      path: '/devcycle'
      fullPath: '/devcycle'
      preLoaderRoute: typeof DevcycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codegen': {
      id: '/codegen'
      path: '/codegen'
      fullPath: '/codegen'
      preLoaderRoute: typeof CodegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architect': {
      id: '/architect'
      path: '/architect'
      fullPath: '/architect'
      preLoaderRoute: typeof ArchitectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/new': {
      id: '/project/new'
      path: '/project/new'
      fullPath: '/project/new'
      preLoaderRoute: typeof ProjectNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagram/editor': {
      id: '/diagram/editor'
      path: '/diagram/editor'
      fullPath: '/diagram/editor'
      preLoaderRoute: typeof DiagramEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/$pipelineId/edit': {
      id: '/pipeline/$pipelineId/edit'
      path: '/$pipelineId/edit'
      fullPath: '/pipeline/$pipelineId/edit'
      preLoaderRoute: typeof PipelinePipelineIdEditRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/p/$slug/settings': {
      id: '/p/$slug/settings'
      path: '/settings'
      fullPath: '/p/$slug/settings'
      preLoaderRoute: typeof PSlugSettingsRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/playpipe': {
      id: '/p/$slug/playpipe'
      path: '/playpipe'
      fullPath: '/p/$slug/playpipe'
      preLoaderRoute: typeof PSlugPlaypipeRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/overview': {
      id: '/p/$slug/overview'
      path: '/overview'
      fullPath: '/p/$slug/overview'
      preLoaderRoute: typeof PSlugOverviewRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/docs': {
      id: '/p/$slug/docs'
      path: '/docs'
      fullPath: '/p/$slug/docs'
      preLoaderRoute: typeof PSlugDocsRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/automations': {
      id: '/p/$slug/automations'
      path: '/automations'
      fullPath: '/p/$slug/automations'
      preLoaderRoute: typeof PSlugAutomationsRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/agents': {
      id: '/p/$slug/agents'
      path: '/agents'
      fullPath: '/p/$slug/agents'
      preLoaderRoute: typeof PSlugAgentsRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/api/notebooklm/notebooks': {
      id: '/api/notebooklm/notebooks'
      path: '/api/notebooklm/notebooks'
      fullPath: '/api/notebooklm/notebooks'
      preLoaderRoute: typeof ApiNotebooklmNotebooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notebooklm/chat': {
      id: '/api/notebooklm/chat'
      path: '/api/notebooklm/chat'
      fullPath: '/api/notebooklm/chat'
      preLoaderRoute: typeof ApiNotebooklmChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/zones': {
      id: '/api/knowledge/zones'
      path: '/api/knowledge/zones'
      fullPath: '/api/knowledge/zones'
      preLoaderRoute: typeof ApiKnowledgeZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/zones/$zoneId': {
      id: '/api/knowledge/zones/$zoneId'
      path: '/$zoneId'
      fullPath: '/api/knowledge/zones/$zoneId'
      preLoaderRoute: typeof ApiKnowledgeZonesZoneIdRouteImport
      parentRoute: typeof ApiKnowledgeZonesRoute
    }
    '/api/knowledge/zones/$zoneId/notebooklm': {
      id: '/api/knowledge/zones/$zoneId/notebooklm'
      path: '/notebooklm'
      fullPath: '/api/knowledge/zones/$zoneId/notebooklm'
      preLoaderRoute: typeof ApiKnowledgeZonesZoneIdNotebooklmRouteImport
      parentRoute: typeof ApiKnowledgeZonesZoneIdRoute
    }
    '/api/knowledge/zones/$zoneId/notebooklm/retry': {
      id: '/api/knowledge/zones/$zoneId/notebooklm/retry'
      path: '/retry'
      fullPath: '/api/knowledge/zones/$zoneId/notebooklm/retry'
      preLoaderRoute: typeof ApiKnowledgeZonesZoneIdNotebooklmRetryRouteImport
      parentRoute: typeof ApiKnowledgeZonesZoneIdNotebooklmRoute
    }
  }
}

interface PipelineRouteChildren {
  PipelinePipelineIdEditRoute: typeof PipelinePipelineIdEditRoute
}

const PipelineRouteChildren: PipelineRouteChildren = {
  PipelinePipelineIdEditRoute: PipelinePipelineIdEditRoute,
}

const PipelineRouteWithChildren = PipelineRoute._addFileChildren(
  PipelineRouteChildren,
)

interface PSlugRouteChildren {
  PSlugAgentsRoute: typeof PSlugAgentsRoute
  PSlugAutomationsRoute: typeof PSlugAutomationsRoute
  PSlugDocsRoute: typeof PSlugDocsRoute
  PSlugOverviewRoute: typeof PSlugOverviewRoute
  PSlugPlaypipeRoute: typeof PSlugPlaypipeRoute
  PSlugSettingsRoute: typeof PSlugSettingsRoute
}

const PSlugRouteChildren: PSlugRouteChildren = {
  PSlugAgentsRoute: PSlugAgentsRoute,
  PSlugAutomationsRoute: PSlugAutomationsRoute,
  PSlugDocsRoute: PSlugDocsRoute,
  PSlugOverviewRoute: PSlugOverviewRoute,
  PSlugPlaypipeRoute: PSlugPlaypipeRoute,
  PSlugSettingsRoute: PSlugSettingsRoute,
}

const PSlugRouteWithChildren = PSlugRoute._addFileChildren(PSlugRouteChildren)

interface ApiKnowledgeZonesZoneIdNotebooklmRouteChildren {
  ApiKnowledgeZonesZoneIdNotebooklmRetryRoute: typeof ApiKnowledgeZonesZoneIdNotebooklmRetryRoute
}

const ApiKnowledgeZonesZoneIdNotebooklmRouteChildren: ApiKnowledgeZonesZoneIdNotebooklmRouteChildren =
  {
    ApiKnowledgeZonesZoneIdNotebooklmRetryRoute:
      ApiKnowledgeZonesZoneIdNotebooklmRetryRoute,
  }

const ApiKnowledgeZonesZoneIdNotebooklmRouteWithChildren =
  ApiKnowledgeZonesZoneIdNotebooklmRoute._addFileChildren(
    ApiKnowledgeZonesZoneIdNotebooklmRouteChildren,
  )

interface ApiKnowledgeZonesZoneIdRouteChildren {
  ApiKnowledgeZonesZoneIdNotebooklmRoute: typeof ApiKnowledgeZonesZoneIdNotebooklmRouteWithChildren
}

const ApiKnowledgeZonesZoneIdRouteChildren: ApiKnowledgeZonesZoneIdRouteChildren =
  {
    ApiKnowledgeZonesZoneIdNotebooklmRoute:
      ApiKnowledgeZonesZoneIdNotebooklmRouteWithChildren,
  }

const ApiKnowledgeZonesZoneIdRouteWithChildren =
  ApiKnowledgeZonesZoneIdRoute._addFileChildren(
    ApiKnowledgeZonesZoneIdRouteChildren,
  )

interface ApiKnowledgeZonesRouteChildren {
  ApiKnowledgeZonesZoneIdRoute: typeof ApiKnowledgeZonesZoneIdRouteWithChildren
}

const ApiKnowledgeZonesRouteChildren: ApiKnowledgeZonesRouteChildren = {
  ApiKnowledgeZonesZoneIdRoute: ApiKnowledgeZonesZoneIdRouteWithChildren,
}

const ApiKnowledgeZonesRouteWithChildren =
  ApiKnowledgeZonesRoute._addFileChildren(ApiKnowledgeZonesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ArchitectRoute: ArchitectRoute,
  CodeRoute: CodeRoute,
  CodegenRoute: CodegenRoute,
  DevcycleRoute: DevcycleRoute,
  DiagramsRoute: DiagramsRoute,
  DocsRoute: DocsRoute,
  GithubRoute: GithubRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  NotebooksRoute: NotebooksRoute,
  ObservabilityRoute: ObservabilityRoute,
  PipelineRoute: PipelineRouteWithChildren,
  PipelinesRoute: PipelinesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SyncRoute: SyncRoute,
  WorkspaceRoute: WorkspaceRoute,
  DiagramEditorRoute: DiagramEditorRoute,
  EditorIdRoute: EditorIdRoute,
  PSlugRoute: PSlugRouteWithChildren,
  ProjectNewRoute: ProjectNewRoute,
  ApiKnowledgeZonesRoute: ApiKnowledgeZonesRouteWithChildren,
  ApiNotebooklmChatRoute: ApiNotebooklmChatRoute,
  ApiNotebooklmNotebooksRoute: ApiNotebooklmNotebooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
