name = "drakon-agent-flue"
main = "src/index.ts"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
PROXY_URL = "https://llm-proxy.fra.appwrite.run"
PROXY_MODEL = "gemini-2.5-flash"

[[kv_namespaces]]
binding = "KNOWLEDGE_BASE"
id = "d4fdc6c83e994032a51be4542b245e27"
preview_id = "d4fdc6c83e994032a51be4542b245e27"
