/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GithubRouteImport } from './routes/github'
import { Route as DiagramsRouteImport } from './routes/diagrams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndexIndexRouteImport } from './routes/index.index'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as DiagramEditorRouteImport } from './routes/diagram.editor'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramsRoute = DiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexIndexRoute = IndexIndexRouteImport.update({
  id: '/index/',
  path: '/index/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramEditorRoute = DiagramEditorRouteImport.update({
  id: '/diagram/editor',
  path: '/diagram/editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/github': typeof GithubRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/diagram/editor': typeof DiagramEditorRoute
  '/editor/$id': typeof EditorIdRoute
  '/index/': typeof IndexIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/github': typeof GithubRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/diagram/editor': typeof DiagramEditorRoute
  '/editor/$id': typeof EditorIdRoute
  '/index': typeof IndexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/github': typeof GithubRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/diagram/editor': typeof DiagramEditorRoute
  '/editor/$id': typeof EditorIdRoute
  '/index/': typeof IndexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagrams'
    | '/github'
    | '/login'
    | '/settings'
    | '/sync'
    | '/diagram/editor'
    | '/editor/$id'
    | '/index/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagrams'
    | '/github'
    | '/login'
    | '/settings'
    | '/sync'
    | '/diagram/editor'
    | '/editor/$id'
    | '/index'
  id:
    | '__root__'
    | '/'
    | '/diagrams'
    | '/github'
    | '/login'
    | '/settings'
    | '/sync'
    | '/diagram/editor'
    | '/editor/$id'
    | '/index/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagramsRoute: typeof DiagramsRoute
  GithubRoute: typeof GithubRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SyncRoute: typeof SyncRoute
  DiagramEditorRoute: typeof DiagramEditorRoute
  EditorIdRoute: typeof EditorIdRoute
  IndexIndexRoute: typeof IndexIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagrams': {
      id: '/diagrams'
      path: '/diagrams'
      fullPath: '/diagrams'
      preLoaderRoute: typeof DiagramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/': {
      id: '/index/'
      path: '/index'
      fullPath: '/index/'
      preLoaderRoute: typeof IndexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagram/editor': {
      id: '/diagram/editor'
      path: '/diagram/editor'
      fullPath: '/diagram/editor'
      preLoaderRoute: typeof DiagramEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagramsRoute: DiagramsRoute,
  GithubRoute: GithubRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SyncRoute: SyncRoute,
  DiagramEditorRoute: DiagramEditorRoute,
  EditorIdRoute: EditorIdRoute,
  IndexIndexRoute: IndexIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
