/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagramsRouteImport } from './routes/diagrams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndexIndexRouteImport } from './routes/index.index'
import { Route as EditorIdRouteImport } from './routes/editor.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramsRoute = DiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexIndexRoute = IndexIndexRouteImport.update({
  id: '/index/',
  path: '/index/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/login': typeof LoginRoute
  '/editor/$id': typeof EditorIdRoute
  '/index/': typeof IndexIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/login': typeof LoginRoute
  '/editor/$id': typeof EditorIdRoute
  '/index': typeof IndexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/login': typeof LoginRoute
  '/editor/$id': typeof EditorIdRoute
  '/index/': typeof IndexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diagrams' | '/login' | '/editor/$id' | '/index/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diagrams' | '/login' | '/editor/$id' | '/index'
  id: '__root__' | '/' | '/diagrams' | '/login' | '/editor/$id' | '/index/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagramsRoute: typeof DiagramsRoute
  LoginRoute: typeof LoginRoute
  EditorIdRoute: typeof EditorIdRoute
  IndexIndexRoute: typeof IndexIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagrams': {
      id: '/diagrams'
      path: '/diagrams'
      fullPath: '/diagrams'
      preLoaderRoute: typeof DiagramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/': {
      id: '/index/'
      path: '/index'
      fullPath: '/index/'
      preLoaderRoute: typeof IndexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagramsRoute: DiagramsRoute,
  LoginRoute: LoginRoute,
  EditorIdRoute: EditorIdRoute,
  IndexIndexRoute: IndexIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
