export interface SolutionFunction {
  name: string;
  path?: string;
  description?: string;
  params?: string[];
}

export interface SolutionModule {
  name: string;
  path?: string;
  functions: SolutionFunction[];
}

export interface Solution {
  project: string;
  language?: "js" | "javascript" | "lua";
  target?: string;
  modules: SolutionModule[];
}

export interface LinkResult {
  code: string;
  targetPath: string;
  language: "js" | "lua";
  warnings: string[];
}

/**
 * Assembles all compiled module functions into a single bundle based on solution.json.
 * 
 * @param solutionJsonStr The raw content of solution.json
 * @param getFile A function to fetch the content of files from the repository
 * @returns Object containing the bundle code, target path, language, and any warnings
 */
export async function linkProject(
  solutionJsonStr: string,
  getFile: (path: string) => Promise<string>
): Promise<LinkResult> {
  let solution: Solution;
  try {
    solution = JSON.parse(solutionJsonStr) as Solution;
  } catch (err) {
    throw new Error(`Помилка парсингу solution.json: ${err instanceof Error ? err.message : String(err)}`);
  }

  if (!solution.project) {
    throw new Error("Некоректний solution.json: відсутнє поле 'project'");
  }

  if (!solution.modules || !Array.isArray(solution.modules)) {
    throw new Error("Некоректний solution.json: поле 'modules' має бути масивом");
  }

  // Determine language (js/javascript or lua)
  let language: "js" | "lua" = "js";
  const solLang = solution.language?.toLowerCase();
  if (solLang === "lua") {
    language = "lua";
  } else if (solLang === "js" || solLang === "javascript") {
    language = "js";
  } else if (solution.target?.endsWith(".lua")) {
    language = "lua";
  }

  // Determine target bundle path
  const defaultTarget = language === "lua" ? "dist/bundle.lua" : "dist/bundle.js";
  const targetPath = solution.target || defaultTarget;

  const warnings: string[] = [];
  const seenFunctions = new Map<string, { moduleName: string; path: string }>();
  const modulesData: Array<{
    moduleName: string;
    functions: Array<{
      name: string;
      code: string;
      path: string;
    }>;
  }> = [];

  // Traverse modules and functions
  for (const mod of solution.modules) {
    const modFunctions: Array<{ name: string; code: string; path: string }> = [];

    for (const func of mod.functions) {
      if (!func.name) {
        warnings.push(`Пропущено функцію без імені в модулі '${mod.name}'`);
        continue;
      }

      // Check for duplicates
      if (seenFunctions.has(func.name)) {
        const prev = seenFunctions.get(func.name)!;
        warnings.push(
          `Конфлікт імен: функція '${func.name}' дублюється в модулі '${mod.name}' (раніше оголошена в '${prev.moduleName}')`
        );
      }

      // Determine path to compiled code
      // If path is specified (e.g. auth/login.drakon), replace .drakon with .js/.lua
      // Otherwise, construct a default path: modules/auth/login.js
      let codePath = "";
      if (func.path) {
        const ext = language === "lua" ? ".lua" : ".js";
        codePath = func.path.replace(/\.drakon$/, ext);
      } else {
        const ext = language === "lua" ? ".lua" : ".js";
        const modPath = mod.path || mod.name;
        codePath = `${modPath}/${func.name}${ext}`;
      }

      seenFunctions.set(func.name, { moduleName: mod.name, path: codePath });

      // Fetch file contents
      try {
        const code = await getFile(codePath);
        modFunctions.push({
          name: func.name,
          code: code.trim(),
          path: codePath,
        });
      } catch (err) {
        throw new Error(
          `Не вдалося завантажити скомпільований код для функції '${func.name}' за шляхом '${codePath}': ${
            err instanceof Error ? err.message : String(err)
          }`
        );
      }
    }

    modulesData.push({
      moduleName: mod.name,
      functions: modFunctions,
    });
  }

  // Generate bundle code
  let bundleCode = "";
  const timestamp = new Date().toISOString();

  if (language === "js") {
    bundleCode = generateJsBundle(solution.project, timestamp, modulesData);
  } else {
    bundleCode = generateLuaBundle(solution.project, timestamp, modulesData);
  }

  return {
    code: bundleCode,
    targetPath,
    language,
    warnings,
  };
}

function generateJsBundle(
  project: string,
  timestamp: string,
  modulesData: Array<{
    moduleName: string;
    functions: Array<{ name: string; code: string; path: string }>;
  }>
): string {
  let output = `// ============================================================================\n`;
  output += `// Bundle generated by AI-DRAKON Linker\n`;
  output += `// Project: ${project}\n`;
  output += `// Generated: ${timestamp}\n`;
  output += `// ============================================================================\n\n`;

  // Write functions by module
  for (const mod of modulesData) {
    output += `// --- Module: ${mod.moduleName} ---\n\n`;
    for (const func of mod.functions) {
      output += `// Source: ${func.path}\n`;
      output += `${func.code}\n\n`;
    }
  }

  // Generate Module exports
  output += `// --- Module Exports ---\n\n`;
  for (const mod of modulesData) {
    if (mod.functions.length === 0) continue;
    
    output += `export const ${mod.moduleName} = {\n`;
    for (const func of mod.functions) {
      output += `  ${func.name},\n`;
    }
    output += `};\n\n`;
  }

  // Generate flat exports
  const flatExports: string[] = [];
  for (const mod of modulesData) {
    for (const func of mod.functions) {
      flatExports.push(func.name);
    }
  }

  if (flatExports.length > 0) {
    output += `export {\n`;
    for (const name of flatExports) {
      output += `  ${name},\n`;
    }
    output += `};\n`;
  }

  return output;
}

function generateLuaBundle(
  project: string,
  timestamp: string,
  modulesData: Array<{
    moduleName: string;
    functions: Array<{ name: string; code: string; path: string }>;
  }>
): string {
  let output = `-- ============================================================================\n`;
  output += `-- Bundle generated by AI-DRAKON Linker\n`;
  output += `-- Project: ${project}\n`;
  output += `-- Generated: ${timestamp}\n`;
  output += `-- ============================================================================\n\n`;

  // Generate forward declarations for Lua so functions can call each other regardless of definition order
  output += `-- --- Forward Declarations ---\n`;
  const allFuncNames: string[] = [];
  for (const mod of modulesData) {
    for (const func of mod.functions) {
      output += `local ${func.name}\n`;
      allFuncNames.push(func.name);
    }
  }
  output += `\n`;

  // Write function bodies (temporarily re-assigning them to local variables)
  for (const mod of modulesData) {
    output += `-- --- Module: ${mod.moduleName} ---\n\n`;
    for (const func of mod.functions) {
      output += `-- Source: ${func.path}\n`;
      
      // If the compiled lua code contains 'function name(...)', we strip 'function ' 
      // and change it to 'name = function(...)' or keep it global depending on structure.
      // But since we did forward declaration 'local name', writing:
      // name = function(...) ... end
      // or simply letting the compiled function be defined without the 'local' keyword:
      // function name(...) ... end
      // works perfectly because Lua resolves 'function name(...)' to the local variable 'name' if it is already in scope!
      // This is an extremely elegant feature of Lua.
      output += `${func.code}\n\n`;
    }
  }

  // Generate Module exports table
  output += `-- --- Module Tables ---\n`;
  for (const mod of modulesData) {
    if (mod.functions.length === 0) continue;
    
    output += `local ${mod.moduleName} = {\n`;
    for (const func of mod.functions) {
      output += `  ${func.name} = ${func.name},\n`;
    }
    output += `}\n\n`;
  }

  // Final return table
  output += `-- --- Return Exports ---\n`;
  output += `return {\n`;
  for (const mod of modulesData) {
    if (mod.functions.length === 0) continue;
    output += `  ${mod.moduleName} = ${mod.moduleName},\n`;
  }
  
  output += `  -- Global flat aliases\n`;
  for (const name of allFuncNames) {
    output += `  ${name} = ${name},\n`;
  }
  output += `}\n`;

  return output;
}
