/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagramsRouteImport } from './routes/diagrams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as DiagramEditorRouteImport } from './routes/diagram.editor'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GithubRouteImport } from './routes/github'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramsRoute = DiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramEditorRoute = DiagramEditorRouteImport.update({
  id: '/diagram/editor',
  path: '/diagram/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/login': typeof LoginRoute
  '/editor/$id': typeof EditorIdRoute
  '/diagram/editor': typeof DiagramEditorRoute
  '/settings': typeof SettingsRoute
  '/github': typeof GithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/login': typeof LoginRoute
  '/editor/$id': typeof EditorIdRoute
  '/diagram/editor': typeof DiagramEditorRoute
  '/settings': typeof SettingsRoute
  '/github': typeof GithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/login': typeof LoginRoute
  '/editor/$id': typeof EditorIdRoute
  '/diagram/editor': typeof DiagramEditorRoute
  '/settings': typeof SettingsRoute
  '/github': typeof GithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagrams'
    | '/login'
    | '/editor/$id'
    | '/diagram/editor'
    | '/settings'
    | '/github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagrams'
    | '/login'
    | '/editor/$id'
    | '/diagram/editor'
    | '/settings'
    | '/github'
  id:
    | '__root__'
    | '/'
    | '/diagrams'
    | '/login'
    | '/editor/$id'
    | '/diagram/editor'
    | '/settings'
    | '/github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagramsRoute: typeof DiagramsRoute
  LoginRoute: typeof LoginRoute
  EditorIdRoute: typeof EditorIdRoute
  DiagramEditorRoute: typeof DiagramEditorRoute
  SettingsRoute: typeof SettingsRoute
  GithubRoute: typeof GithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagrams': {
      id: '/diagrams'
      path: '/diagrams'
      fullPath: '/diagrams'
      preLoaderRoute: typeof DiagramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagram/editor': {
      id: '/diagram/editor'
      path: '/diagram/editor'
      fullPath: '/diagram/editor'
      preLoaderRoute: typeof DiagramEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagramsRoute: DiagramsRoute,
  LoginRoute: LoginRoute,
  EditorIdRoute: EditorIdRoute,
  DiagramEditorRoute: DiagramEditorRoute,
  SettingsRoute: SettingsRoute,
  GithubRoute: GithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
