// Generated by OpenDesign (antigravity + ai-drakon-mobile plugin)
// http://192.168.3.184:7460/ → project: ai-drakon
import React from 'react';
import { Home, Bot, GitBranch, Settings } from 'lucide-react';
import { NavLink } from 'react-router-dom';

const MobileNavBar = () => {
  const navItems = [
    { name: 'Home', path: '/', icon: Home },
    { name: 'Bot', path: '/bot', icon: Bot },
    { name: 'Project', path: '/branches', icon: GitBranch },
    { name: 'Settings', path: '/settings', icon: Settings },
  ];

  return (
    <nav className="fixed bottom-0 left-0 right-0 z-50 md:hidden bg-black/60 backdrop-blur-lg border-t border-white/10 safe-area-pb">
      <div className="flex justify-around items-center h-16">
        {navItems.map((item) => (
          <NavLink
            key={item.name}
            to={item.path}
            className={({ isActive }) =>
              `flex flex-col items-center justify-center w-full h-full transition-colors ${
                isActive ? 'text-white' : 'text-zinc-500 hover:text-zinc-300'
              }`
            }
          >
            <item.icon size={24} strokeWidth={1.5} />
            <span className="text-[10px] mt-1 font-medium">{item.name}</span>
          </NavLink>
        ))}
      </div>
    </nav>
  );
};

export default MobileNavBar;
